FROM node:20-alpine

WORKDIR /app

COPY ../../frontend/web/package.json /app/package.json
COPY ../../frontend/web/package-lock.json /app/package-lock.json

RUN npm install

COPY ../../frontend/web /app

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
